bootstrap.servers=kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092
source.topic=order-created
customer.topic=customer-created
cancelled.topic=order-cancelled
payment.topic=payment-init
group.id=order-service-group
db.path=/data/orders.db
ui.port=8081
