bootstrap.servers=kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092
order.topic=order-created
customer.topic=customer-created
order.service.url=http://kafka-order-service:8081
db.path=/data/portal.db
port=8082
